server:
  port: 8099
spring:
  mvc:
  static-path-pattern: /**
  datasource:
    medical:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@localhost:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: test
      password: test


    pacs:
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://localhost:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: root
#      password: 12345678
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://localhost:1433;DatabaseName=RIS_BASIC
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: test
      password: test


    ecg:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@localhost:1521:jhrecg
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: test
      password: test

logging:
  config: classpath:logback-boot.xml


