server:
  port: 8099
spring:
  mvc:
  static-path-pattern: /**
  datasource:
    medical:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@10.20.13.80:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: wxjdfymedical
      password: wxjdfymedical


    pacs:
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://localhost:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: root
#      password: 12345678
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://10.20.13.1:1433;DatabaseName=RIS_BASIC
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: ris
      password: Wxsy@6789


    ecg:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@10.20.13.4:1521:jhrecg
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: slpt
      password: slpt

logging:
  config: classpath:logback-boot.xml


